import { Market, MarketStatus, Position, Duel, Order } from './types';

export const MOCK_MARKETS: Market[] = [
  {
    id: '1',
    title: 'Solana hits $250 by end of May?',
    description: 'Predict if Solana (SOL) will reach a market price of $250 USD on any major exchange by May 31, 2026, 23:59 UTC.',
    category: 'Crypto',
    imageUrl: 'https://images.unsplash.com/photo-1639454121453-167a4d89805d?q=80&w=800&auto=format&fit=crop',
    status: MarketStatus.OPEN,
    poolAmount: 1540.5,
    yesAmount: 850.2,
    noAmount: 690.3,
    currency: 'SOL',
    oracleId: 'switchboard-sol-price',
    createdAt: Date.now() - 86400000 * 2,
    cutoffAt: Date.now() + 86400000 * 30,
  },
  {
    id: '2',
    title: 'GPT-5 released before developers conference?',
    description: 'Will OpenAI officially announce the release of GPT-5 before their next major developer conference?',
    category: 'AI',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=800&auto=format&fit=crop',
    status: MarketStatus.ACTIVE,
    poolAmount: 3200.0,
    yesAmount: 1200.0,
    noAmount: 2000.0,
    currency: 'SOL',
    oracleId: 'switchboard-openai-news',
    createdAt: Date.now() - 86400000 * 10,
    cutoffAt: Date.now() - 3600000,
  },
  {
    id: '3',
    title: 'Real Madrid vs Man City - UCL Final',
    description: 'Who will win the UEFA Champions League Final?',
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800&auto=format&fit=crop',
    status: MarketStatus.OPEN,
    poolAmount: 5000.0,
    yesAmount: 2500.0,
    noAmount: 2500.0,
    currency: 'SOL',
    oracleId: 'switchboard-ucl-result',
    createdAt: Date.now() - 86400000,
    cutoffAt: Date.now() + 86400000 * 5,
  },
  {
    id: '4',
    title: '[SPECIAL] LYNX Market Governance: Grant #1',
    description: 'Should LYNX Market approve the initial grant of 1M $LYNX to the core development pool?',
    category: 'Governance',
    imageUrl: 'https://images.unsplash.com/photo-1512351735230-a07ebdf5b5e1?q=80&w=800&auto=format&fit=crop',
    status: MarketStatus.OPEN,
    poolAmount: 10000,
    yesAmount: 8000,
    noAmount: 2000,
    currency: 'LYNX',
    oracleId: 'lynx-governance-01',
    createdAt: Date.now() - 86400000 * 3,
    cutoffAt: Date.now() + 86400000 * 14,
  }
];

export const MOCK_DUELS: Duel[] = [
  {
    id: 'd1',
    parentMarketId: '1',
    creator: '9xy1...Zp3',
    amount: 10.0,
    currency: 'SOL',
    status: MarketStatus.OPEN,
    positionA: Position.YES,
    positionB: Position.NO,
    createdAt: Date.now() - 3600000 * 2,
  },
  {
    id: 'd2',
    parentMarketId: '3',
    creator: 'Alice...r4t',
    rival: 'Bob...p9q',
    amount: 50.0,
    currency: 'SOL',
    status: MarketStatus.ACTIVE,
    positionA: Position.YES,
    positionB: Position.NO,
    createdAt: Date.now() - 3600000 * 10,
    acceptedAt: Date.now() - 3600000 * 8,
  },
  {
    id: 'd3',
    parentMarketId: '4',
    creator: 'Charlie...LYN',
    amount: 500.0,
    currency: 'LYNX',
    status: MarketStatus.OPEN,
    positionA: Position.YES,
    positionB: Position.NO,
    createdAt: Date.now() - 3600000,
  }
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'o1',
    marketId: '1',
    owner: '9xy1...Zp3',
    side: 'SELL',
    position: Position.YES,
    amount: 100,
    price: 0.55,
    createdAt: Date.now() - 60000,
  },
  {
    id: 'o2',
    marketId: '1',
    owner: 'Ar2q...Lp0',
    side: 'BUY',
    position: Position.YES,
    amount: 50,
    price: 0.52,
    createdAt: Date.now() - 120000,
  },
  {
    id: 'o3',
    marketId: '1',
    owner: 'Kk8u...Ww1',
    side: 'SELL',
    position: Position.YES,
    amount: 250,
    price: 0.58,
    createdAt: Date.now() - 300000,
  }
];

export const STATUS_COLORS: Record<MarketStatus, string> = {
  [MarketStatus.OPEN]: 'text-cyan-400 bg-cyan-400/10 border-cyan-400/20',
  [MarketStatus.ACTIVE]: 'text-emerald-400 bg-emerald-400/10 border-emerald-400/20',
  [MarketStatus.CUT_OFF]: 'text-amber-400 bg-amber-400/10 border-amber-400/20',
  [MarketStatus.RESOLVED]: 'text-purple-400 bg-purple-400/10 border-purple-400/20',
  [MarketStatus.EXPIRED]: 'text-slate-400 bg-slate-400/10 border-slate-400/20',
};


